version: '3.8'
services:
  ursim:
    image: universalrobots/ursim_e-series:5.12.5
    stdin_open: true
    tty: true  
    ports:
      - "5900:5900"
      - "6080:6080"
      - "29999:29999"
      - "30000:30000"
      - "30001:30001"
    environment:
      - ROBOT_MODEL=UR10
    restart: unless-stopped
