#!/usr/bin/env python3
"""End-to-end check of the RealSense Pick program node's URScript on a real controller.

The node's script is generated by the URCap's own ``PickScript`` (compiled from the
sources with the JDK), wrapped the way a program would run it, and executed on an
e-Series controller over Primary; the controller talks over a real TCP socket to a
pick server on this machine that answers from a synthetic block scene (one white
block, the camera at the flange looking down). Passing means the controller parsed
and ran every line — survey ``movej``, ``FIND``, the closer look, the ``REFINE`` lean
ladder with its own IK checks, hover, grip, the child nodes, the lift — and set the
result variable.

    uv run python urcap/pick5_e2e.py                 # the x86 VM sim: scripts/ursim-e-vm.sh up
    uv run python urcap/pick5_e2e.py --host 10.0.0.5 --reach-back 192.168.3.10   # other sims

``--reach-back`` is the address the *controller* uses to reach this machine
(10.0.2.2 from inside the QEMU VM; the docker network's gateway for a local URSim
container, where ``--bind`` must be that address too so the container can connect).
``--dash-port`` / ``--primary-port`` reach a sim published on offset ports
(``urcap/ps5_matrix.py``). It moves the arm: a simulator only.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from perception.picknode import PickPlanner, PickServer, parse_request  # noqa: E402
from tests.test_pickcycle import H, K, W, scene  # noqa: E402
from tests.test_urcap5 import HARNESS, JAVA  # noqa: E402
from urctl import Robot, RobotConfig  # noqa: E402
from urctl.pose import Transform  # noqa: E402

READY = [0.0, -1.0, 1.2, -1.8, -1.5708, 0.0]  # elbow bent, tool down: no singular movel


class World:
    """The synthetic block, fixed in the base frame. The first request's view is exactly
    ``scene([BOX])`` (camera = flange, the hand-eye is identity); every later view — the
    node's closer, tilted look — is ray-cast from the flange pose its request carries, so
    REFINE finds the block where FIND put it, as a real camera would."""

    def __init__(self, box=(40, 30, 70, 54), floor=0.40, height=0.04):
        self.box, self.floor, self.top = box, floor, floor - height
        self.frame: Transform | None = None  # the first view: defines the world
        self.flange: list[float] | None = None  # the newest request's flange pose

    def view(self, line: str) -> None:
        try:
            flange = parse_request(line).get("flange")
        except Exception:  # noqa: BLE001 — the planner itself answers a bad request
            return
        if flange:
            self.flange = flange
            self.frame = self.frame or Transform.from_pose(flange)

    def render(self) -> tuple[bytes, bytes]:
        if self.frame is None or self.flange is None:
            return scene([self.box])
        f0, cam = self.frame, Transform.from_pose(self.flange)
        n, o0 = f0.rotate((0, 0, 1)), f0.apply((0, 0, 0))
        a1, a2 = f0.rotate((1, 0, 0)), f0.rotate((0, 1, 0))
        x0, y0, x1, y1 = self.box
        dot = lambda a, b: a[0] * b[0] + a[1] * b[1] + a[2] * b[2]  # noqa: E731
        o = cam.apply((0, 0, 0))
        h_top, h_floor, h_o = dot(n, o0) + self.top, dot(n, o0) + self.floor, dot(n, o)
        rgb, depth = bytearray(b"\x80\x70\x50" * (W * H)), bytearray(W * H * 2)
        for v in range(H):
            for u in range(W):
                d = cam.rotate(((u - K["ppx"]) / K["fx"], (v - K["ppy"]) / K["fy"], 1.0))
                den = dot(n, d)
                if den <= 1e-6:
                    continue
                t = (h_top - h_o) / den  # the ray has camera-z 1: t is the depth
                q = [o[i] + t * d[i] - o0[i] for i in range(3)]
                i = v * W + u
                # the hit, as a pixel of the first view (1e-9: that view is exactly scene())
                u0 = dot(a1, q) / self.top * K["fx"] + K["ppx"] + 1e-9
                v0 = dot(a2, q) / self.top * K["fy"] + K["ppy"] + 1e-9
                if t > 0 and x0 <= u0 < x1 and y0 <= v0 < y1:
                    rgb[3 * i : 3 * i + 3] = b"\xf0\xf0\xf2"
                else:
                    t = (h_floor - h_o) / den
                mm = max(0, min(65535, int(round(t / 0.001))))
                depth[2 * i], depth[2 * i + 1] = mm & 0xFF, mm >> 8
        return bytes(rgb), bytes(depth)


def generate(host: str, port: int, children: str) -> str:
    javac = shutil.which("javac")
    if not javac:
        raise SystemExit("needs a JDK (javac) to build the node's PickScript")
    root = Path(tempfile.mkdtemp(prefix="pick5-e2e-"))
    pkg = root / "src" / "com" / "olympuscontrols" / "realsensepilot"
    pkg.mkdir(parents=True)
    (pkg / "Harness.java").write_text(HARNESS, encoding="utf-8")
    for name in ("Json.java", "Cockpit.java", "PickScript.java"):
        shutil.copy(JAVA / name, pkg / name)
    subprocess.run(
        [javac, "--release", "8", "-Xlint:-options", "-d", str(root / "c"), *map(str, pkg.glob("*.java"))],
        check=True,
        capture_output=True,
    )
    spec = {"host": host, "port": port, "q": READY, "u": -1, "v": -1, "children": children}
    out = subprocess.run(
        [
            "java",
            "-cp",
            str(root / "c"),
            "com.olympuscontrols.realsensepilot.Harness",
            "pick",
            json.dumps(spec),
        ],
        check=True,
        capture_output=True,
    )
    res = json.loads(out.stdout)
    if res["problem"]:
        raise SystemExit(f"PickScript refused: {res['problem']}")
    return res["script"]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--host", default="127.0.0.1", help="the simulator (Primary/Dashboard)")
    ap.add_argument("--reach-back", default="10.0.2.2", help="this machine, as the controller reaches it")
    ap.add_argument("--port", type=int, default=7623, help="pick server port for the run")
    ap.add_argument("--bind", default="127.0.0.1", help="pick server bind address")
    ap.add_argument("--dash-port", type=int, default=None, help="default UR_DASH_PORT or 29999")
    ap.add_argument("--primary-port", type=int, default=None, help="default UR_PRIMARY_PORT or 30001")
    args = ap.parse_args()
    ports = {"dashboard_port": args.dash_port, "primary_port": args.primary_port}

    world = World()
    seq = {"n": 0}

    def source(after):
        seq["n"] = max(seq["n"], after) + 1
        rgb, depth = world.render()
        return seq["n"], W, H, 3, rgb, depth, 0.001, K

    log: list[str] = []
    planner = PickPlanner(
        source,
        lambda: seq["n"],
        lambda: [0.0] * 6,
        tip_m=0.163,
        min_radius_m=0.0,
        log=lambda text, ok: log.append(text),
    )
    answer = planner.answer
    planner.answer = lambda line: (world.view(line), answer(line))[1]
    server = PickServer(args.bind, args.port, planner)
    server.start()
    try:
        robot = Robot(RobotConfig.from_env(host=args.host, **{k: v for k, v in ports.items() if v}))
        up = robot.bring_up()
        print("bring-up:", up.get("ok"), up.get("robot_mode") or "", up.get("safety_mode") or "")
        children = '      textmsg("rs_e2e/child=", get_actual_tcp_pose())'
        body = generate(args.reach_back, args.port, children)
        body += 'textmsg("rs_e2e/found=", rs_pick_found)\n'
        t0 = time.monotonic()
        captured = robot.primary.run_and_capture(
            body, fn_name="rs_e2e", marker="", collect_for=240.0, stop_marker="rs_e2e/found="
        )
        took = time.monotonic() - t0
    finally:
        server.stop()
    marks = [c for c in captured if "rs_e2e/" in c or "RealSense Pick" in c]
    print(f"ran {took:.1f} s")
    print("pick server:", *log, sep="\n  ")
    print("controller:", *marks, sep="\n  ")
    found = any("rs_e2e/found=True" in c.replace(" ", "") for c in captured)
    child = any("rs_e2e/child=" in c for c in captured)
    ok = (
        found
        and child
        and any(t.startswith("pick FIND: found") for t in log)
        and any(t.startswith("pick REFINE: found") for t in log)
    )
    print("PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
