#!/usr/bin/env python3
"""End-to-end check of the RealSense Pick program node's URScript on a real controller.

The node's script is generated by the URCap's own ``PickScript`` (compiled from the
sources with the JDK), wrapped the way a program would run it, and executed on an
e-Series controller over Primary; the controller talks over a real TCP socket to a
pick server on this machine that answers from a synthetic block scene (one white
block, the camera at the flange looking down). Passing means the controller parsed
and ran every line — survey ``movej``, ``FIND``, the closer look, the ``REFINE`` lean
ladder with its own IK checks, hover, grip, the child nodes, the lift — and set the
result variable.

    uv run python urcap/pick5_e2e.py                 # the x86 VM sim: scripts/ursim-e-vm.sh up
    uv run python urcap/pick5_e2e.py --host 10.0.0.5 --reach-back 192.168.3.10   # other sims

``--reach-back`` is the address the *controller* uses to reach this machine
(10.0.2.2 from inside the QEMU VM). It moves the arm: a simulator only.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from perceptronics.picknode import PickPlanner, PickServer  # noqa: E402
from tests.test_pickcycle import H, K, W, scene  # noqa: E402
from tests.test_urcap5 import HARNESS, JAVA  # noqa: E402
from urctl import Robot, RobotConfig  # noqa: E402

READY = [0.0, -1.0, 1.2, -1.8, -1.5708, 0.0]  # elbow bent, tool down: no singular movel


def generate(host: str, port: int, children: str) -> str:
    javac = shutil.which("javac")
    if not javac:
        raise SystemExit("needs a JDK (javac) to build the node's PickScript")
    root = Path(tempfile.mkdtemp(prefix="pick5-e2e-"))
    pkg = root / "src" / "com" / "olympuscontrols" / "realsensepilot"
    pkg.mkdir(parents=True)
    (pkg / "Harness.java").write_text(HARNESS, encoding="utf-8")
    for name in ("Json.java", "Cockpit.java", "PickScript.java"):
        shutil.copy(JAVA / name, pkg / name)
    subprocess.run(
        [javac, "--release", "8", "-Xlint:-options", "-d", str(root / "c"), *map(str, pkg.glob("*.java"))],
        check=True,
        capture_output=True,
    )
    spec = {"host": host, "port": port, "q": READY, "u": -1, "v": -1, "children": children}
    out = subprocess.run(
        [
            "java",
            "-cp",
            str(root / "c"),
            "com.olympuscontrols.realsensepilot.Harness",
            "pick",
            json.dumps(spec),
        ],
        check=True,
        capture_output=True,
    )
    res = json.loads(out.stdout)
    if res["problem"]:
        raise SystemExit(f"PickScript refused: {res['problem']}")
    return res["script"]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--host", default="127.0.0.1", help="the simulator (Primary/Dashboard)")
    ap.add_argument("--reach-back", default="10.0.2.2", help="this machine, as the controller reaches it")
    ap.add_argument("--port", type=int, default=7623, help="pick server port for the run")
    args = ap.parse_args()

    frame = scene([(40, 30, 70, 54)])
    seq = {"n": 0}

    def source(after):
        seq["n"] = max(seq["n"], after) + 1
        return seq["n"], W, H, 3, frame[0], frame[1], 0.001, K

    log: list[str] = []
    planner = PickPlanner(
        source,
        lambda: seq["n"],
        lambda: [0.0] * 6,
        tip_m=0.163,
        min_radius_m=0.0,
        log=lambda text, ok: log.append(text),
    )
    server = PickServer("127.0.0.1", args.port, planner)
    server.start()
    try:
        robot = Robot(RobotConfig(host=args.host))
        up = robot.bring_up()
        print("bring-up:", up.get("ok"), up.get("robot_mode") or "", up.get("safety_mode") or "")
        children = '      textmsg("rs_e2e/child=", get_actual_tcp_pose())'
        body = generate(args.reach_back, args.port, children)
        body += 'textmsg("rs_e2e/found=", rs_pick_found)\n'
        t0 = time.monotonic()
        captured = robot.primary.run_and_capture(
            body, fn_name="rs_e2e", marker="", collect_for=240.0, stop_marker="rs_e2e/found="
        )
        took = time.monotonic() - t0
    finally:
        server.stop()
    marks = [c for c in captured if "rs_e2e/" in c or "RealSense Pick" in c]
    print(f"ran {took:.1f} s")
    print("pick server:", *log, sep="\n  ")
    print("controller:", *marks, sep="\n  ")
    found = any("rs_e2e/found=True" in c.replace(" ", "") for c in captured)
    child = any("rs_e2e/child=" in c for c in captured)
    ok = (
        found
        and child
        and any(t.startswith("pick FIND: found") for t in log)
        and any(t.startswith("pick REFINE: found") for t in log)
    )
    print("PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
