#!/usr/bin/env python3
"""End-to-end check of the 3D Pick program node's URScript on a real controller.

The node's script is generated by the URCap's own ``PickScript`` (compiled from the
sources with the JDK), wrapped the way a program would run it, and executed on an
e-Series controller over Primary; the controller talks over a real TCP socket to a
pick server on this machine that answers from a ray-cast scene: two parts of the node's
default size (50 x 30 x 30 mm) on a table 0.40 m below the picture point, fixed in the
base frame, the camera at the flange. The node runs **three times**: the first run surveys
from the picture point (``NEXT`` → nothing queued → ``movej`` → ``FIND``), the second
takes the other part from the queue (``NEXT`` → straight to the closer look, from where the
first run left the arm: at the grip), the third with the closer look switched off (always
the picture point, ``REFINE`` from there). Passing means the controller parsed and ran
every line — the survey, ``FIND``, the closer look, the ``REFINE`` lean ladder with its own
IK checks, the approach, the descent to the grip — each time, and set the result and
location variables. The node drives no gripper (0.8.0): there is none to simulate.

    python3 urcap/pick5_e2e.py                 # the x86 VM sim: scripts/ursim-e-vm.sh up
    python3 urcap/pick5_e2e.py --host 10.0.0.5 --reach-back 192.168.3.10   # other sims

``--reach-back`` is the address the *controller* uses to reach this machine
(10.0.2.2 from inside the QEMU VM; the docker network's gateway for a local URSim
container, where ``--bind`` must be that address too so the container can connect).
``--dash-port`` / ``--primary-port`` reach a sim published on offset ports
(``urcap/ps5_matrix.py``). It moves the arm: a simulator only.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from perceptronics.picknode import PickPlanner, PickServer, parse_request  # noqa: E402
from perceptronics.synthscene import Box, render_depth  # noqa: E402
from tests.test_urcap5 import HARNESS, JAVA, PURE_JAVA, SCREEN_JAVA  # noqa: E402
from urctl import Robot, RobotConfig  # noqa: E402
from urctl.pose import Transform  # noqa: E402

W, H = 320, 180
K = {"fx": 230.0, "fy": 230.0, "ppx": W / 2, "ppy": H / 2}
READY = [0.0, -1.0, 1.2, -1.8, -1.5708, 0.0]  # elbow bent, tool down: no singular movel


class World:
    """Two parts fixed in the base frame, placed from the first FIND's flange pose (the
    picture point): the table 0.40 m below it, the parts 35 mm either side of straight
    below. Every view is ray-cast from the flange pose its request carries."""

    def __init__(self, table_below=0.40):
        self.table_below = table_below
        self.boxes: list[Box] = []
        self.table_z = 0.0
        self.flange: list[float] | None = None

    def view(self, line: str) -> None:
        try:
            req = parse_request(line)
        except Exception:  # noqa: BLE001 — the planner itself answers a bad request
            return
        flange = req.get("flange")
        if not flange:
            return
        self.flange = flange
        # the parts lie under the picture point: the first FIND, not the NEXT sent from
        # wherever the arm was when the program started
        if not self.boxes and req.get("verb") == "FIND":
            x, y, z = flange[:3]
            self.table_z = z - self.table_below
            self.boxes = [Box(x - 0.035, y, 0.05, 0.03, 0.03, 0.2), Box(x + 0.035, y, 0.05, 0.03, 0.03, 0.2)]

    def depth(self) -> bytes:
        if self.flange is None:
            return bytes(W * H * 2)
        return render_depth(W, H, K, Transform.from_pose(self.flange), self.boxes, table_z=self.table_z)


def generate(spec: dict) -> str:
    javac = shutil.which("javac")
    if not javac:
        raise SystemExit("needs a JDK (javac) to build the node's PickScript")
    root = Path(tempfile.mkdtemp(prefix="pick5-e2e-"))
    pkg = root / "src" / "io" / "advin" / "perceptronic"
    pkg.mkdir(parents=True)
    (pkg / "Harness.java").write_text(HARNESS, encoding="utf-8")
    for name in (*PURE_JAVA, *SCREEN_JAVA):  # the harness lays the screens out too
        shutil.copy(JAVA / name, pkg / name)
    subprocess.run(
        [
            javac,
            "--release",
            "8",
            "-Xlint:-options",
            "-encoding",
            "UTF-8",
            "-d",
            str(root / "c"),
            *map(str, pkg.glob("*.java")),
        ],
        check=True,
        capture_output=True,
    )
    out = subprocess.run(
        [
            "java",
            "-cp",
            str(root / "c"),
            "io.advin.perceptronic.Harness",
            "pick",
            json.dumps(spec),
        ],
        check=True,
        capture_output=True,
    )
    res = json.loads(out.stdout)
    if res["problem"]:
        raise SystemExit(f"PickScript refused: {res['problem']}")
    return res["script"]


def verdict(captured: list[str], log: list[str]) -> dict[str, bool]:
    """What the three runs must have left behind — in the controller's messages (``captured``)
    and in the pick server's log: each run ended holding a part, the second took its part
    from the queue, and the third (the closer look off) never asked for a look pose."""
    flat = [c.replace(" ", "") for c in captured]
    return {
        "first run ends at the grip": any("rs_e2e/first=True" in c for c in flat),
        "it came from picture point 1": any("rs_e2e/loc=1" in c for c in flat),
        "second run ends at the grip": any("rs_e2e/found=True" in c for c in flat),
        "second run took it from the queue": any("nextpartalreadyseen" in c for c in flat)
        and any(t.startswith("pick NEXT [e2e001]: found") for t in log),
        "third run (no closer look) ends at the grip": any("rs_e2e/nolook=True" in c for c in flat),
        "two surveys found the part": sum(1 for t in log if t.startswith("pick FIND [e2e001]: found")) >= 2,
        "every run re-measured it": sum(1 for t in log if t.startswith("pick REFINE [e2e001]: found")) >= 3,
        # the first two runs take the closer look; the third never asks for one
        "two closer looks, not three": sum(1 for t in log if t.startswith("pick LOOK: found")) == 2,
    }


ERRORS = re.compile(r"(?i)error|exception|not defined|unknown|illegal|syntax|invalid")


def compile_probe(robot: Robot, spec: dict) -> tuple[bool, bool]:
    """Does the controller *compile* the part of the script the run above can't reach — the
    failure popup (``popup(..., blocking=True)``)? The script goes inside ``if False:`` so nothing
    runs; URControl compiles the whole program first, so a function or keyword argument this
    controller lacks means the marker after it never prints. The control: a dead branch that
    calls a function no controller has must *not* print its marker, or the probe proves
    nothing on this controller (returned as the second value)."""
    control = robot.primary.run_and_capture(
        'if False:\n  rs_e2e_no_such_function()\nend\ntextmsg("rs_e2e/control=", True)\n',
        fn_name="rs_e2e_control",
        marker="",
        collect_for=15.0,
        stop_marker="rs_e2e/control=",
    )
    control_ran = any("rs_e2e/control=" in c for c in control)
    full = generate({**spec, "popup": True})
    body = "if False:\n" + full + "end\n" + 'textmsg("rs_e2e/compiled=", True)\n'
    captured = robot.primary.run_and_capture(
        body, fn_name="rs_e2e_probe", marker="", collect_for=30.0, stop_marker="rs_e2e/compiled="
    )
    compiled = any("rs_e2e/compiled=" in c for c in captured)
    for c in control + captured:
        if ERRORS.search(c):
            print("  controller:", c)
    return compiled, control_ran


def polyscope_version(robot: Robot) -> list[int] | None:
    """The controller's PolyScope ``[major, minor, bugfix]`` — what the node reads from
    ``SystemAPI.getSoftwareVersion()`` on a pendant (Dashboard ``PolyscopeVersion``:
    ``URSoftware 5.9.4.1031232 (...)``)."""
    try:
        reply = robot.dashboard.command("PolyscopeVersion")
    except OSError:
        return None
    m = re.search(r"([0-9]+)\.([0-9]+)\.([0-9]+)", reply)
    return [int(g) for g in m.groups()] if m else None


def timeout_probe(robot: Robot, host: str, port: int) -> bool:
    """The node's error paths lean on ``socket_read_ascii_float`` timing out (status -8): does
    a timed-out read of 16 numbers land in a list that already holds 17 without stopping the
    program? (An older controller keeps a list at its first size.) The pick server stays
    silent until it reads a line, so the read times out."""
    body = (
        "rs_r = [16, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]\n"
        f'if socket_open("{host}", {port}, "rs_to"):\n'
        '  rs_r = socket_read_ascii_float(16, "rs_to", 0.5)\n'
        '  socket_close("rs_to")\n'
        "end\n"
        'textmsg("rs_e2e/timeout=", rs_r[0])\n'
    )
    captured = robot.primary.run_and_capture(
        body, fn_name="rs_e2e_timeout", marker="", collect_for=20.0, stop_marker="rs_e2e/timeout="
    )
    for c in captured:
        if ERRORS.search(c) or "rs_e2e/timeout=" in c:
            print("  controller:", c)
    return any("rs_e2e/timeout=" in c for c in captured)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--host", default="127.0.0.1", help="the simulator (Primary/Dashboard)")
    ap.add_argument("--reach-back", default="10.0.2.2", help="this machine, as the controller reaches it")
    ap.add_argument("--port", type=int, default=7623, help="pick server port for the run")
    ap.add_argument("--bind", default="127.0.0.1", help="pick server bind address")
    ap.add_argument("--dash-port", type=int, default=None, help="default UR_DASH_PORT or 29999")
    ap.add_argument("--primary-port", type=int, default=None, help="default UR_PRIMARY_PORT or 30001")
    args = ap.parse_args()
    ports = {"dashboard_port": args.dash_port, "primary_port": args.primary_port}

    world = World()
    seq = {"n": 0}

    def source(after):
        seq["n"] = max(seq["n"], after) + 1
        return seq["n"], W, H, 3, bytes(W * H * 3), world.depth(), 0.001, K

    log: list[str] = []
    planner = PickPlanner(
        source,
        lambda: seq["n"],
        lambda: [0.0] * 6,
        tip_m=0.163,
        min_radius_m=0.0,
        log=lambda text, ok: log.append(text),
    )
    answer = planner.answer
    planner.answer = lambda line: (world.view(line), answer(line))[1]
    server = PickServer(args.bind, args.port, planner)
    server.start()
    try:
        robot = Robot(RobotConfig.from_env(host=args.host, **{k: v for k, v in ports.items() if v}))
        up = robot.bring_up()
        print("bring-up:", up.get("ok"), up.get("robot_mode") or "", up.get("safety_mode") or "")
        version = polyscope_version(robot)
        print(
            "PolyScope:",
            ".".join(map(str, version)) if version else "unknown (the script assumes the newest)",
        )
        spec = {
            "host": args.reach_back,
            "port": args.port,
            "node": "e2e001",
            "points": [{"q": READY}],
            "popup": False,  # a blocking popup would hold the run until someone taps it
            **({"polyscope": version} if version else {}),
        }
        once = generate(spec)
        no_look = generate({**spec, "closeLook": False})
        body = once + 'textmsg("rs_e2e/first=", rs_pick_found)\n'
        body += 'textmsg("rs_e2e/loc=", rs_pick_loc)\n'
        body += once + 'textmsg("rs_e2e/found=", rs_pick_found)\n'
        body += no_look + 'textmsg("rs_e2e/nolook=", rs_pick_found)\n'
        t0 = time.monotonic()
        captured = robot.primary.run_and_capture(
            body, fn_name="rs_e2e", marker="", collect_for=420.0, stop_marker="rs_e2e/nolook="
        )
        took = time.monotonic() - t0
        compiled, control = compile_probe(robot, spec)
        timed_out = timeout_probe(robot, args.reach_back, args.port)
    finally:
        server.stop()
    marks = [c for c in captured if "rs_e2e/" in c or "3D Pick" in c]
    print(f"ran {took:.1f} s")
    print("pick server:", *log, sep="\n  ")
    print("controller:", *marks, sep="\n  ")
    for c in captured:
        if ERRORS.search(c) and "rs_e2e" not in c:
            print("  controller:", c)
    ok = all(verdict(captured, log).values())
    for what, good in verdict(captured, log).items():
        print(f"  {'ok  ' if good else 'FAIL'}  {what}")
    print("controller compiles the full script (with the popup):", compiled)
    if control:
        print("  (inconclusive: this controller also ran a dead branch naming an undefined function)")
    print("a timed-out read into a 16-number list leaves the program running:", timed_out)
    ok = ok and compiled and timed_out
    print("PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
