"""urp_builder — author *native* PolyScope `.urp` programs as a node tree.

WHY THIS EXISTS (and how it differs from ``urp_convert``)
---------------------------------------------------------
``scripts/urp_convert.py`` wraps a whole ``.script`` in a single
``<Script type="File">`` node. PolyScope loads it, but the operator sees one
opaque "Script" line — not an editable program. That is the right tool when
you already have URScript and just need it to appear in the file browser.

This module is the other direction: when *we* author the program, we emit the
**typed node tree** PolyScope itself produces — ``<Move>``/``<Waypoint>``,
``<If>``, ``<Loop>``, ``<Set>``, ``<Folder>``, ``<Comment>``, ``<Popup>`` — so
opening the result shows real, point-and-click UR program nodes. The hybrid
"load key functions and use them" pattern is supported directly: drop helper
``def``\\ s in a :meth:`UrpProgram.script_file` node and call them from
:meth:`UrpProgram.script_line` nodes, which render as ordinary script lines.

PROVENANCE — every node shape here was verified to LOAD into URSim 5.12.x
-----------------------------------------------------------------------
The node grammar below was not guessed; each tag/attribute set was confirmed
by generating a ``.urp`` and watching ``load`` succeed (and ``programState``
report it) against the running URSim container, the same empirical method that
produced ``urp_convert``'s schema. Two findings worth recording because they
cost real time:

  * **The kinematics envelope matters for ``<Script>`` nodes.** A program with
    real (UR10e) ``<kinematics>`` and ``jointChecksum="-1,…"`` loads fine for
    Move/Waypoint nodes but makes ``ScriptNodeConversionStrategy`` reject the
    program ("not a valid file version"). The *all-zero, NOT_LINEARIZED*
    envelope (identical to ``urp_convert``'s) loads every node type, so that is
    what we emit unconditionally. Joint-space waypoints don't need calibrated
    kinematics anyway.
  * **Not every node type round-trips through a guessed schema.** ``<Wait>``
    and ``<Script type="Code">`` were tried and rejected by their conversion
    strategies; they are intentionally *absent* here rather than shipped
    broken. Add them only after teaching one in PolyScope and diffing the save.

USAGE
-----
    from urctl.urp_builder import UrpProgram, Waypoint

    prog = UrpProgram("Pick")
    prog.comment("Generated by urctl")
    with prog.folder("Setup"):
        prog.set_output(0, True)
    prog.movej(Waypoint("Approach", q=[-1.6, -1.72, -2.2, -0.8, 1.595, -0.03]))
    with prog.if_digital_in(0, True):
        prog.movel(Waypoint("Grasp", q=[-1.6, -1.9, -2.16, -0.68, 1.595, -0.03]))
    with prog.loop(3):
        prog.movej(Waypoint("Tap", q=[-1.6, -1.72, -2.2, -0.8, 1.595, -0.03]))
    prog.script_file("helpers", "def retract():\\n  movel(...)\\nend\\n")
    prog.script_line("retract()")
    prog.popup("Cycle complete")
    prog.save("programs/Pick/Pick.urp")   # pair with a <name>.installation
"""

from __future__ import annotations

import gzip
from collections.abc import Iterator, Sequence
from contextlib import AbstractContextManager, contextmanager
from dataclasses import dataclass, field
from pathlib import Path
from xml.sax.saxutils import escape

# Reuse urp_convert's version constants so the two emitters stay in lockstep on
# the header PolyScope stamps into every program. Bootstrap scripts/ onto the
# path (the vendored copy in the wheel, else scripts/ from a source checkout).
try:
    from urp_convert import DEFAULT_CREATED_IN, DEFAULT_LAST_SAVED_IN
except ImportError:  # pragma: no cover - exercised only outside an install
    import sys

    _scripts = Path(__file__).resolve().parent.parent / "scripts"
    if _scripts.is_dir():  # source checkout
        if str(_scripts) not in sys.path:
            sys.path.insert(0, str(_scripts))
        from urp_convert import DEFAULT_CREATED_IN, DEFAULT_LAST_SAVED_IN
    else:  # installed wheel: build-time vendored copy
        from urctl._urp_convert import DEFAULT_CREATED_IN, DEFAULT_LAST_SAVED_IN

# The all-zero, checksum-disabled kinematics that loads with every node type
# (see module docstring). Real calibration is robot-specific and unnecessary
# for joint-space waypoints on URSim.
_ZERO6 = "0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
_KINEMATICS = (
    '<kinematics status="NOT_LINEARIZED" validChecksum="false">'
    f'<deltaTheta value="{_ZERO6}"/>'
    f'<a value="{_ZERO6}"/>'
    f'<d value="{_ZERO6}"/>'
    f'<alpha value="{_ZERO6}"/>'
    '<jointChecksum value="0, 0, 0, 0, 0, 0"/>'
    "</kinematics>"
)
# Per-waypoint kinematics block uses the capitalised tag PolyScope emits.
_WP_KINEMATICS = _KINEMATICS.replace("<kinematics", "<Kinematics").replace("</kinematics>", "</Kinematics>")

# The default feature reference PolyScope's default.installation exposes; every
# Move node points its frame at it. Pairs with the default.installation this
# repo copies alongside generated programs.
_DEFAULT_FEATURE = "Joint_0_name"


def _attr(value: str) -> str:
    """Escape a value for use inside a double-quoted XML attribute."""
    return escape(value, {'"': "&quot;"})


def _fmt_joints(q: Sequence[float]) -> str:
    if len(q) != 6:
        raise ValueError(f"joint vector must have 6 elements, got {len(q)}: {q!r}")
    return ", ".join(str(float(v)) for v in q)


def _indent(lines: list[str], level: int) -> list[str]:
    pad = "  " * level
    return [pad + ln for ln in lines]


# --------------------------------------------------------------------------- #
# Nodes. Each renders to a list of (un-indented) XML lines; the program walks
# the tree applying indentation. Container nodes hold `children`.
# --------------------------------------------------------------------------- #


class _Node:
    def render(self) -> list[str]:  # pragma: no cover - interface
        raise NotImplementedError


@dataclass
class Waypoint:
    """A fixed, joint-space teach point. ``q`` is six joint angles (radians).

    Cartesian waypoints exist in PolyScope too, but joint-space points are
    unambiguous and need no calibration to replay, so that is what we emit.

    ``blend_radius`` (metres) rounds the corner at this point so the robot keeps
    momentum through it instead of stopping. ``None`` (the default) emits an
    empty ``<motionParameters/>`` — the waypoint uses the Move node's shared
    parameters and comes to rest (a *stopping point*). Set a value to override
    the blend for this point only; speed/acceleration stay shared with the Move
    node. The XML shape (``blendRadius`` as a ``<motionParameters>`` attribute)
    is taken from the controller's own ``WaypointNodeConversionStrategy`` (it
    reads it back via ``getDoubleAttribute("blendRadius")``), not guessed.
    Remember: a blend on the *final* waypoint of a move is a URScript error, and
    a radius larger than half the shortest adjacent segment aborts the move
    ("blend radius too large for segment") — see the best-practices doc.
    """

    name: str
    q: Sequence[float]
    blend_radius: float | None = None

    def __post_init__(self) -> None:
        if len(self.q) != 6:
            raise ValueError(f"joint vector must have 6 elements, got {len(self.q)}: {self.q!r}")
        if self.blend_radius is not None and self.blend_radius < 0:
            raise ValueError(f"blend_radius must be >= 0 metres, got {self.blend_radius!r}")

    def render(self) -> list[str]:
        motion_params = (
            f'<motionParameters blendRadius="{float(self.blend_radius)}"/>'
            if self.blend_radius is not None
            else "<motionParameters/>"
        )
        return [
            f'<Waypoint type="Fixed" name="{_attr(self.name)}" kinematicsFlags="4">',
            f"  {motion_params}",
            "  <position>",
            f'    <JointAngles angles="{_fmt_joints(self.q)}"/>',
            f'    <TCPOffset pose="{_ZERO6}"/>',
            f"    {_WP_KINEMATICS}",
            "  </position>",
            f'  <BaseToFeature pose="{_ZERO6}"/>',
            "</Waypoint>",
        ]


@dataclass
class _Move(_Node):
    motion_type: str  # "MoveJ" | "MoveL"
    waypoints: list[Waypoint]
    speed: float
    acceleration: float

    def render(self) -> list[str]:
        out = [
            f'<Move motionType="{self.motion_type}" speed="{self.speed}" '
            f'acceleration="{self.acceleration}" useActiveTCP="true" '
            'positionType="CartesianPose">',
            f'  <feature class="GeomFeatureReference" referencedName="{_DEFAULT_FEATURE}"/>',
            "  <children>",
        ]
        for wp in self.waypoints:
            out += _indent(wp.render(), 2)
        out += ["  </children>", "</Move>"]
        return out


@dataclass
class _Comment(_Node):
    text: str

    def render(self) -> list[str]:
        return [f'<Comment comment="{_attr(self.text)}"/>']


@dataclass
class _Popup(_Node):
    message: str
    halt: bool
    warning: bool
    error: bool

    def render(self) -> list[str]:
        return [
            f'<Popup type="Message" haltProgram="{str(self.halt).lower()}" '
            f'warning="{str(self.warning).lower()}" error="{str(self.error).lower()}">',
            f"  <message>{escape(self.message)}</message>",
            "</Popup>",
        ]


@dataclass
class _SetOutput(_Node):
    bit: int
    value: bool

    def render(self) -> list[str]:
        return [f'<Set type="DigitalOutput" outputBit="{self.bit}" outputValue="{str(self.value).lower()}"/>']


@dataclass
class _ScriptLine(_Node):
    """A single URScript statement, shown as one script line in the tree."""

    expression: str

    def render(self) -> list[str]:
        return [
            '<Script type="Line">',
            f'  <expression><ExpressionToken token="{_attr(self.expression)}"/></expression>',
            "</Script>",
        ]


@dataclass
class _ScriptFile(_Node):
    """An embedded script file node — the carrier for multi-line helper defs.

    ``contents`` is raw URScript (e.g. one or more ``def … end`` blocks); the
    ``source`` path is recorded for PolyScope's "saved from" metadata and does
    not need to exist on disk for the program to load.
    """

    contents: str
    source: str

    def render(self) -> list[str]:
        # cachedContents holds verbatim multi-line text; escape() handles & < >.
        return [
            '<Script type="File">',
            f"  <cachedContents>{escape(self.contents)}</cachedContents>",
            f'  <file resolves-to="file">{escape(self.source)}</file>',
            "</Script>",
        ]


@dataclass
class _Container(_Node):
    """Base for nodes that hold a <children> block (Folder/If/Loop)."""

    children: list[_Node] = field(default_factory=list)

    def _open(self) -> list[str]:  # pragma: no cover - interface
        raise NotImplementedError

    def _close(self) -> list[str]:  # pragma: no cover - interface
        raise NotImplementedError

    def render(self) -> list[str]:
        out = self._open() + ["  <children>"]
        for child in self.children:
            out += _indent(child.render(), 2)
        out += ["  </children>"] + self._close()
        return out


@dataclass
class _Folder(_Container):
    name: str = "Folder"

    def _open(self) -> list[str]:
        return [f'<Folder name="{_attr(self.name)}" keepSynchronizedWithDisk="false">']

    def _close(self) -> list[str]:
        return ["</Folder>"]


@dataclass
class _If(_Container):
    expression: str = "True"

    def _open(self) -> list[str]:
        return [
            '<If type="If" checkContinuously="false">',
            f'  <expression><ExpressionToken token="{_attr(self.expression)}"/></expression>',
        ]

    def _close(self) -> list[str]:
        return ["</If>"]


@dataclass
class _Loop(_Container):
    count: int = 1

    def _open(self) -> list[str]:
        return [f'<Loop type="Counting" loopType="Counting" feedVariable="false" loopNum="{self.count}">']

    def _close(self) -> list[str]:
        return ["</Loop>"]


# --------------------------------------------------------------------------- #
# Builder
# --------------------------------------------------------------------------- #

# PolyScope default jog-ish speeds; MoveJ in rad, rad/s^2, MoveL in m/s, m/s^2.
_DEFAULT_MOVEJ_SPEED = 1.0471975511965976
_DEFAULT_MOVEJ_ACCEL = 1.3962634015954636
_DEFAULT_MOVEL_SPEED = 0.25
_DEFAULT_MOVEL_ACCEL = 1.2


class UrpProgram:
    """Build a native-node-tree PolyScope ``.urp`` program.

    Leaf methods (``movej``, ``comment``, ``popup`` …) append to the current
    nesting level. Container methods (``folder``, ``if_expr``/``if_digital_in``,
    ``loop``) are context managers — nodes added inside the ``with`` block
    become that container's children::

        with prog.loop(3):
            prog.movej(Waypoint("Tap", q=[...]))   # nested under the loop
    """

    def __init__(
        self,
        name: str,
        *,
        installation: str = "default",
        directory: str = "/programs",
        run_only_once: bool = True,
    ) -> None:
        self.name = name
        self.installation = installation
        self.directory = directory
        self.run_only_once = run_only_once
        self._root: list[_Node] = []
        # Stack of the children list currently being appended to.
        self._stack: list[list[_Node]] = [self._root]

    # -- internal --------------------------------------------------------- #

    def _add(self, node: _Node) -> _Node:
        self._stack[-1].append(node)
        return node

    @contextmanager
    def _nest(self, container: _Container) -> Iterator[_Container]:
        self._add(container)
        self._stack.append(container.children)
        try:
            yield container
        finally:
            self._stack.pop()

    # -- leaf nodes ------------------------------------------------------- #

    def comment(self, text: str) -> None:
        self._add(_Comment(text))

    def _add_move(
        self, motion_type: str, waypoints: list[Waypoint], speed: float, acceleration: float, group: bool
    ) -> None:
        """Add a Move node, or extend the trailing one when ``group`` is set.

        Grouping merges this move's waypoints into the immediately-preceding Move
        node at the current nesting level *only* if it has the same motion type
        and identical speed/acceleration — so consecutive same-type moves become
        one editable Move node, but a different speed (or an intervening node like
        a Set/Comment) starts a fresh node, matching how PolyScope groups moves.
        """
        if group:
            siblings = self._stack[-1]
            if (
                siblings
                and isinstance(siblings[-1], _Move)
                and siblings[-1].motion_type == motion_type
                and siblings[-1].speed == speed
                and siblings[-1].acceleration == acceleration
            ):
                siblings[-1].waypoints.extend(waypoints)
                return
        self._add(_Move(motion_type, waypoints, speed, acceleration))

    def movej(
        self,
        *waypoints: Waypoint,
        speed: float = _DEFAULT_MOVEJ_SPEED,
        acceleration: float = _DEFAULT_MOVEJ_ACCEL,
        group: bool = False,
    ) -> None:
        """Add a MoveJ (joint-interpolated) move through one or more waypoints.

        With ``group=True`` the waypoints are merged into a preceding compatible
        MoveJ node instead of opening a new one (see :meth:`_add_move`)."""
        if not waypoints:
            raise ValueError("movej requires at least one Waypoint")
        self._add_move("MoveJ", list(waypoints), speed, acceleration, group)

    def movel(
        self,
        *waypoints: Waypoint,
        speed: float = _DEFAULT_MOVEL_SPEED,
        acceleration: float = _DEFAULT_MOVEL_ACCEL,
        group: bool = False,
    ) -> None:
        """Add a MoveL (straight-line) move through one or more waypoints.

        With ``group=True`` the waypoints are merged into a preceding compatible
        MoveL node instead of opening a new one (see :meth:`_add_move`)."""
        if not waypoints:
            raise ValueError("movel requires at least one Waypoint")
        self._add_move("MoveL", list(waypoints), speed, acceleration, group)

    def set_output(self, bit: int, value: bool) -> None:
        """Set a standard digital output."""
        self._add(_SetOutput(bit, value))

    def popup(self, message: str, *, halt: bool = False, warning: bool = False, error: bool = False) -> None:
        self._add(_Popup(message, halt, warning, error))

    def script_line(self, expression: str) -> None:
        """Add one URScript statement as a script line (e.g. a helper call)."""
        self._add(_ScriptLine(expression))

    def script_file(self, name: str, contents: str) -> None:
        """Embed raw URScript (helper ``def``\\ s) as a script-file node.

        ``name`` is used only to synthesize the recorded source path; call the
        defined functions from :meth:`script_line` nodes that follow.
        """
        self._add(_ScriptFile(contents, f"{self.directory}/{name}.script"))

    # -- containers (context managers) ----------------------------------- #

    def folder(self, name: str) -> AbstractContextManager[_Container]:
        return self._nest(_Folder(name=name))

    def if_expr(self, expression: str) -> AbstractContextManager[_Container]:
        """Open an If whose condition is a raw URScript boolean expression."""
        return self._nest(_If(expression=expression))

    def if_digital_in(self, bit: int, value: bool = True) -> AbstractContextManager[_Container]:
        """Open an If gated on a standard digital input (convenience over if_expr)."""
        return self._nest(_If(expression=f"get_standard_digital_in({bit}) == {value}"))

    def loop(self, count: int) -> AbstractContextManager[_Container]:
        """Open a counting Loop that repeats its children ``count`` times."""
        return self._nest(_Loop(count=count))

    # -- emit ------------------------------------------------------------- #

    def to_xml(self) -> str:
        if len(self._stack) != 1:
            raise RuntimeError("unbalanced container nesting — a 'with' block was left open")
        body: list[str] = []
        for node in self._root:
            body += _indent(node.render(), 4)
        return (
            '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
            f'<URProgram name="{_attr(self.name)}" '
            f'installation="{_attr(self.installation)}" '
            f'installationRelativePath="{_attr(self.installation)}" '
            f'directory="{_attr(self.directory)}" '
            f'createdIn="{_attr(DEFAULT_CREATED_IN)}" '
            f'lastSavedIn="{_attr(DEFAULT_LAST_SAVED_IN)}" '
            'robotSerialNumber="">\n'
            f"  {_KINEMATICS}\n"
            "  <children>\n"
            f'    <MainProgram runOnlyOnce="{str(self.run_only_once).lower()}" '
            'InitVariablesNode="false">\n'
            "      <children>\n" + ("\n".join(body) + "\n" if body else "") + "      </children>\n"
            "    </MainProgram>\n"
            "  </children>\n"
            "</URProgram>\n"
        )

    def to_bytes(self) -> bytes:
        """Return the gzipped ``.urp`` bytes PolyScope loads."""
        return gzip.compress(self.to_xml().encode("utf-8"))

    def save(self, path: str | Path) -> Path:
        """Write the ``.urp`` to ``path``. Remember to pair it with a sibling
        ``<installation>.installation`` file or PolyScope will refuse to load it."""
        p = Path(path)
        p.write_bytes(self.to_bytes())
        return p


__all__ = ["UrpProgram", "Waypoint"]
